<?php
include('Function.php');

if(is_login() == TRUE){
	echo "Welcome ".$_SESSION['myusername'];
	echo '<a href="views/login/logout.php">Logout</a>';
	
}else{
	echo '<a href="views/login/main_login.php">Login</a>';
}

require_once 'libs/Twig/Autoloader.php';
Twig_Autoloader::register();

$loader = new Twig_Loader_Filesystem('modules/templates');
$twig = new Twig_Environment($loader);


$header = 'Welcome to COMP 353 - New HELLO THERE';
$msg = 'This website is setup by Charles Yang through shell on September 26, 2012. And it is generated by Twig.';

echo $twig->render('index.twig', array('title' => 'COMP 353 - Database', 'header' => $header, 'msg' => $msg));
?>